env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
  - plugin:svelte/recommended
overrides:
  - files: ['*.svelte']
    processor: 'svelte/svelte'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: ['error', 2, {'SwitchCase': 1}]
  valid-jsdoc: 'off'
  require-jsdoc: 'off'
  camelcase: 'off'
