useTabs: false
tabWidth: 2
bracketSpacing: false
singleQuote: true
trailingComma: 'all'
printWidth: 80
semi: true
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss # MUST come last

